
#pragma once

#define TF_LOCATION_SERVICE_NAME_MAXLEN		257
#define TF_LOCATION_SERVICE_ID_MAXLEN		37
#define TF_LOCATION_SERVICE_REL_PATH_MAXLEN	257
#define TF_LOCATION_SERVICE_TOOL_TYPE_MAXLEN	257
#define TF_LOCATION_SERVICE_TYPE_MAXLEN		257

typedef struct {
	char id[TF_LOCATION_SERVICE_ID_MAXLEN];
	char type[TF_LOCATION_SERVICE_TYPE_MAXLEN];
	char name[TF_LOCATION_SERVICE_NAME_MAXLEN];
	int reltosetting;
	char relpath[TF_LOCATION_SERVICE_REL_PATH_MAXLEN];
	int singleton;
	char *description;
	char tooltype[TF_LOCATION_SERVICE_TOOL_TYPE_MAXLEN];
} tf_location_service_t;

